In [1]:
from sklearn import preprocessing 
from sklearn.linear_model import LogisticRegression
import numpy as np
X = np.array([[ 0.,    0.,    0.],
              [ 1.5,   2.5,   3.5],
              [ -1.5, -2.5,  -3.5]])


test_X = np.array([[ 1.,    1.,    1.],
              [ 1.5,   2.5,   3.5],
              [ -1.4, -2.4,  -3.4]])
"""

trainY = np.array([
       [1],
       [1],
       [1],
       [1       ],
       [1        ],
       [1        ],
       [0        ],
       [0       ],
       [0        ]])
"""


trainY = np.array([0, 0, 0, 1, 1, 1, 0, 0, 0])


# calculate mean
X_mean = X.mean(axis=0)
print("mean\n", X_mean, "\n")
# calculate variance 
X_std = X.std(axis=0)
print("std\n", X_std, "\n")
# standardize X --- Z transform
X1 = (X-X_mean)/X_std
print(X1)
X_scale = preprocessing.scale(X)
X_scale

mean
 [0. 0. 0.] 

std
 [1.22474487 2.04124145 2.85773803] 

[[ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


array([[ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487],
       [-1.22474487, -1.22474487, -1.22474487]])

In [2]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minMax = min_max_scaler.fit_transform(X)
print(X_minMax)
## X_minMax_reshape = min_max_scaler.fit_transform(X).reshape(-1, 1) 
X_minMax_reshape = min_max_scaler.fit_transform(X).reshape(-1, 1)
test_X_minMax_reshape = min_max_scaler.fit_transform(test_X).reshape(-1, 1)
#utils.multiclass.type_of_target(X_minMax_reshape)
print(X_minMax_reshape)
estimator = LogisticRegression()
estimator.fit(X_minMax_reshape, trainY)
pred = estimator.predict(test_X_minMax_reshape)
pred

[[0.5 0.5 0.5]
 [1.  1.  1. ]
 [0.  0.  0. ]]
[[0.5]
 [0.5]
 [0.5]
 [1. ]
 [1. ]
 [1. ]
 [0. ]
 [0. ]
 [0. ]]


C:\Users\Chenj\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0, 0, 0, 1, 1, 1, 0, 0, 0])