In [1]:
from sklearn import preprocessing 
import numpy as np
X = np.array([[ 1.,    2.,    3.],
              [ 1.5,   2.5,   3.5],
              [ -1.5, -2.5,  -3.5]])
# calculate mean
X_mean = X.mean(axis=0)
print("mean\n", X_mean, "\n")
# calculate variance 
X_std = X.std(axis=0)
print("std\n", X_std, "\n")
# standardize X
X1 = (X-X_mean)/X_std
print(X1)
X_scale = preprocessing.scale(X)
X_scale

mean
 [0.33333333 0.66666667 1.        ] 

std
 [1.31233465 2.24845626 3.18852108] 

[[ 0.50800051  0.59299945  0.62725005]
 [ 0.88900089  0.81537425  0.78406256]
 [-1.3970014  -1.4083737  -1.41131261]]


array([[ 0.50800051,  0.59299945,  0.62725005],
       [ 0.88900089,  0.81537425,  0.78406256],
       [-1.3970014 , -1.4083737 , -1.41131261]])

In [3]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minMax = min_max_scaler.fit_transform(X)
print(X_minMax)
X_minMax_reshape = min_max_scaler.fit_transform(X).reshape(-1, 1)
X_minMax_reshape

[[0.83333333 0.9        0.92857143]
 [1.         1.         1.        ]
 [0.         0.         0.        ]]


array([[0.83333333],
       [0.9       ],
       [0.92857143],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ]])